name: my_todo_pipeline

on:
  push:
    branches:
      - main
      - ci/cd
  pull_request:
    
jobs:
    build-and-push-docker:
      runs-on: ubuntu-latest
      env:
        WORK_DIR: ./todo-app

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Log in to Docker-Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and push frontend Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:latest $WORK_DIR/frontend
            docker push ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:latest
          
        - name: Build and push backend Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:latest $WORK_DIR/backend
            docker push ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:latest
          
