name: my_todo_pipeline

on:
  push:
    branches:
      - main
      - ci/cd
  pull_request:
    
jobs:
    build-and-push-docker:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Log in to Docker-Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Go to project directory
          run: cd /home/runner/work/MyToDo/MyToDo/todo-app | ls
        
        - name: Actual dierectory
          run: pwd
        
        - name: Build and push frontend Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:latest ./frontend
            docker push ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:latest
          
        - name: Build and push backend Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:latest ./backend
            docker push ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:latest
          
